module.exports.reseller = require('./reseller.js')
module.exports.scheduling = require('./scheduling.js')
module.exports.oauth2 = require('./oAuth2.js')
module.exports.account = require('./account.js')
module.exports.chat = require('./chat.js')
module.exports.call_tracking = require('./call_tracking.js')
